system('R -d  "valgrind --track-origins=yes --leak-check=full" -f tests/grindy/test.R 2>&1 | tee tests/grindy/valgrind')

vg <- readLines("tests/grindy/valgrind")
as.integer(gsub("\\)", "", unlist(lapply(strsplit(grep("vapour\\.cpp:", vg, value = TRUE), "\\.cpp:"), "[", 2)))) -> idx
tx <- readLines("src/vapour.cpp")
tx[idx]

## from exportToJson:
## The returned string should be freed with CPLFree() when no longer required.


## no more ExecuteSQL leaks:
## no more exportTo[Text] leaks:
[1] "  long long nFeature_long = poLayer->GetFeatureCount();"
[2] "  long long nFeature_long = poLayer->GetFeatureCount();"
[3] "  long long nFeature_long = poLayer->GetFeatureCount();"
[4] "  long long nFeature_long = poLayer->GetFeatureCount();"
[5] "  long long nFeature_long = poLayer->GetFeatureCount();"
[6] "  long long nFeature_long = poLayer->GetFeatureCount();"
[7] "  long long nFeature_long = poLayer->GetFeatureCount();"
[8] "  long long nFeature_long = poLayer->GetFeatureCount();"
[9] "  long long nFeature_long = poLayer->GetFeatureCount();"
[10] "  long long nFeature_long = poLayer->GetFeatureCount();"
[11] "  long long nFeature_long = poLayer->GetFeatureCount();"
[12] "  long long nFeature_long = poLayer->GetFeatureCount();"
[13] "  long long nFeature_long = poLayer->GetFeatureCount();"
[14] "  long long nFeature_long = poLayer->GetFeatureCount();"
[15] "  long long nFeature_long = poLayer->GetFeatureCount();"
[16] "  long long nFeature_long = poLayer->GetFeatureCount();"
[17] "  long long nFeature_long = poLayer->GetFeatureCount();"
[18] "  long long nFeature_long = poLayer->GetFeatureCount();"
[19] "  long long nFeature_long = poLayer->GetFeatureCount();"
[20] "  long long nFeature_long = poLayer->GetFeatureCount();"
[21] "  long long nFeature_long = poLayer->GetFeatureCount();"
[22] "  long long nFeature_long = poLayer->GetFeatureCount();"
[23] "  long long nFeature_long = poLayer->GetFeatureCount();"
[24] "  long long nFeature_long = poLayer->GetFeatureCount();"
[25] "  long long nFeature_long = poLayer->GetFeatureCount();"
[26] "  long long nFeature_long = poLayer->GetFeatureCount();"
[27] "  long long nFeature_long = poLayer->GetFeatureCount();"
[28] "  long long nFeature_long = poLayer->GetFeatureCount();"
[29] "  long long nFeature_long = poLayer->GetFeatureCount();"
[30] "  long long nFeature_long = poLayer->GetFeatureCount();"
[31] "  long long nFeature_long = poLayer->GetFeatureCount();"
[32] "  long long nFeature_long = poLayer->GetFeatureCount();"
[33] "  long long nFeature_long = poLayer->GetFeatureCount();"
[34] "  long long nFeature_long = poLayer->GetFeatureCount();"
[35] "  long long nFeature_long = poLayer->GetFeatureCount();"
[36] "  long long nFeature_long = poLayer->GetFeatureCount();"
[37] "  long long nFeature_long = poLayer->GetFeatureCount();"
[38] "  long long nFeature_long = poLayer->GetFeatureCount();"
[39] "  long long nFeature_long = poLayer->GetFeatureCount();"
[40] "  long long nFeature_long = poLayer->GetFeatureCount();"
[41] "  long long nFeature_long = poLayer->GetFeatureCount();"
[42] "  long long nFeature_long = poLayer->GetFeatureCount();"
[43] "  long long nFeature_long = poLayer->GetFeatureCount();"
[44] "  long long nFeature_long = poLayer->GetFeatureCount();"
[45] "  long long nFeature_long = poLayer->GetFeatureCount();"
[46] "  long long nFeature_long = poLayer->GetFeatureCount();"
[47] "  long long nFeature_long = poLayer->GetFeatureCount();"
[48] "  long long nFeature_long = poLayer->GetFeatureCount();"
[49] "  long long nFeature_long = poLayer->GetFeatureCount();"
[50] "  long long nFeature_long = poLayer->GetFeatureCount();"
[51] "  long long nFeature_long = poLayer->GetFeatureCount();"
[52] "  long long nFeature_long = poLayer->GetFeatureCount();"
[53] "  long long nFeature_long = poLayer->GetFeatureCount();"
[54] "  long long nFeature_long = poLayer->GetFeatureCount();"
[55] "  long long nFeature_long = poLayer->GetFeatureCount();"
[56] "  long long nFeature_long = poLayer->GetFeatureCount();"
[57] "  long long nFeature_long = poLayer->GetFeatureCount();"
[58] "  long long nFeature_long = poLayer->GetFeatureCount();"
[59] "  long long nFeature_long = poLayer->GetFeatureCount();"
[60] "  long long nFeature_long = poLayer->GetFeatureCount();"
[61] "  long long nFeature_long = poLayer->GetFeatureCount();"
[62] "  long long nFeature_long = poLayer->GetFeatureCount();"
[63] "  long long nFeature_long = poLayer->GetFeatureCount();"
[64] "  long long nFeature_long = poLayer->GetFeatureCount();"
[65] "  long long nFeature_long = poLayer->GetFeatureCount();"
[66] "  long long nFeature_long = poLayer->GetFeatureCount();"
[67] "  long long nFeature_long = poLayer->GetFeatureCount();"
[68] "  long long nFeature_long = poLayer->GetFeatureCount();"
[69] "  long long nFeature_long = poLayer->GetFeatureCount();"
[70] "  long long nFeature_long = poLayer->GetFeatureCount();"
[71] "  long long nFeature_long = poLayer->GetFeatureCount();"
[72] "  long long nFeature_long = poLayer->GetFeatureCount();"
[73] "  long long nFeature_long = poLayer->GetFeatureCount();"
[74] "  long long nFeature_long = poLayer->GetFeatureCount();"
[75] "  long long nFeature_long = poLayer->GetFeatureCount();"
[76] "  long long nFeature_long = poLayer->GetFeatureCount();"
[77] "  long long nFeature_long = poLayer->GetFeatureCount();"
[78] "  long long nFeature_long = poLayer->GetFeatureCount();"
[79] "  long long nFeature_long = poLayer->GetFeatureCount();"
[80] "  long long nFeature_long = poLayer->GetFeatureCount();"
[81] "  long long nFeature_long = poLayer->GetFeatureCount();"
[82] "  long long nFeature_long = poLayer->GetFeatureCount();"
[83] "  long long nFeature_long = poLayer->GetFeatureCount();"
[84] "  long long nFeature_long = poLayer->GetFeatureCount();"
[85] "  long long nFeature_long = poLayer->GetFeatureCount();"
[86] "  long long nFeature_long = poLayer->GetFeatureCount();"
[87] "  long long nFeature_long = poLayer->GetFeatureCount();"
[88] "  long long nFeature_long = poLayer->GetFeatureCount();"
[89] "  long long nFeature_long = poLayer->GetFeatureCount();"
[90] "  long long nFeature_long = poLayer->GetFeatureCount();"
[91] "  long long nFeature_long = poLayer->GetFeatureCount();"
[92] "  long long nFeature_long = poLayer->GetFeatureCount();"
[93] "  long long nFeature_long = poLayer->GetFeatureCount();"
[94] "  long long nFeature_long = poLayer->GetFeatureCount();"
[95] "  while( (poFeature = poLayer->GetNextFeature()) != NULL && lFeature < nFeature)"
[96] "  long long nFeature_long = poLayer->GetFeatureCount();"
[97] "  while( (poFeature = poLayer->GetNextFeature()) != NULL && lFeature < nFeature)"
>
