// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// 000-stream.cpp
list gdal_dsn_read_vector_stream(cpp11::sexp stream_xptr, strings dsn, strings layer, strings sql, std::vector<std::string> options, bool quiet, std::vector<std::string> drivers, doubles extent, bool dsn_exists, strings fid_column_name, int width);
extern "C" SEXP _vapour_gdal_dsn_read_vector_stream(SEXP stream_xptr, SEXP dsn, SEXP layer, SEXP sql, SEXP options, SEXP quiet, SEXP drivers, SEXP extent, SEXP dsn_exists, SEXP fid_column_name, SEXP width) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_vector_stream(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(stream_xptr), cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<strings>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<std::vector<std::string>>>(options), cpp11::as_cpp<cpp11::decay_t<bool>>(quiet), cpp11::as_cpp<cpp11::decay_t<std::vector<std::string>>>(drivers), cpp11::as_cpp<cpp11::decay_t<doubles>>(extent), cpp11::as_cpp<cpp11::decay_t<bool>>(dsn_exists), cpp11::as_cpp<cpp11::decay_t<strings>>(fid_column_name), cpp11::as_cpp<cpp11::decay_t<int>>(width)));
  END_CPP11
}
// 000-warpgeneral.cpp
list warp_general_cpp(strings dsn, strings target_crs, doubles target_extent, integers target_dim, doubles target_res, integers bands, strings resample, logicals silent, strings band_output_type, strings options, strings dsn_outname, logicals include_meta, logicals nara);
extern "C" SEXP _vapour_warp_general_cpp(SEXP dsn, SEXP target_crs, SEXP target_extent, SEXP target_dim, SEXP target_res, SEXP bands, SEXP resample, SEXP silent, SEXP band_output_type, SEXP options, SEXP dsn_outname, SEXP include_meta, SEXP nara) {
  BEGIN_CPP11
    return cpp11::as_sexp(warp_general_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<strings>>(target_crs), cpp11::as_cpp<cpp11::decay_t<doubles>>(target_extent), cpp11::as_cpp<cpp11::decay_t<integers>>(target_dim), cpp11::as_cpp<cpp11::decay_t<doubles>>(target_res), cpp11::as_cpp<cpp11::decay_t<integers>>(bands), cpp11::as_cpp<cpp11::decay_t<strings>>(resample), cpp11::as_cpp<cpp11::decay_t<logicals>>(silent), cpp11::as_cpp<cpp11::decay_t<strings>>(band_output_type), cpp11::as_cpp<cpp11::decay_t<strings>>(options), cpp11::as_cpp<cpp11::decay_t<strings>>(dsn_outname), cpp11::as_cpp<cpp11::decay_t<logicals>>(include_meta), cpp11::as_cpp<cpp11::decay_t<logicals>>(nara)));
  END_CPP11
}
// 000-warpgeneral.cpp
list warp_suggest_cpp(strings dsn, strings target_crs);
extern "C" SEXP _vapour_warp_suggest_cpp(SEXP dsn, SEXP target_crs) {
  BEGIN_CPP11
    return cpp11::as_sexp(warp_suggest_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<strings>>(target_crs)));
  END_CPP11
}
// 00_config.cpp
integers set_gdal_config_cpp(strings option, strings value);
extern "C" SEXP _vapour_set_gdal_config_cpp(SEXP option, SEXP value) {
  BEGIN_CPP11
    return cpp11::as_sexp(set_gdal_config_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(option), cpp11::as_cpp<cpp11::decay_t<strings>>(value)));
  END_CPP11
}
// 00_config.cpp
strings get_gdal_config_cpp(strings option);
extern "C" SEXP _vapour_get_gdal_config_cpp(SEXP option) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_gdal_config_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(option)));
  END_CPP11
}
// 00_gdal.cpp
logicals cleanup_gdal_cpp();
extern "C" SEXP _vapour_cleanup_gdal_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(cleanup_gdal_cpp());
  END_CPP11
}
// 00_gdal.cpp
strings driver_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_driver_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(driver_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_gdal.cpp
strings driver_id_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_driver_id_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(driver_id_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_gdal.cpp
strings layer_names_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_layer_names_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(layer_names_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_gdal.cpp
list drivers_list_gdal_cpp();
extern "C" SEXP _vapour_drivers_list_gdal_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(drivers_list_gdal_cpp());
  END_CPP11
}
// 00_gdal.cpp
strings proj_to_wkt_gdal_cpp(strings proj4string);
extern "C" SEXP _vapour_proj_to_wkt_gdal_cpp(SEXP proj4string) {
  BEGIN_CPP11
    return cpp11::as_sexp(proj_to_wkt_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(proj4string)));
  END_CPP11
}
// 00_gdal.cpp
logicals crs_is_lonlat_cpp(strings input_string);
extern "C" SEXP _vapour_crs_is_lonlat_cpp(SEXP input_string) {
  BEGIN_CPP11
    return cpp11::as_sexp(crs_is_lonlat_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(input_string)));
  END_CPP11
}
// 00_gdal.cpp
logicals register_gdal_cpp();
extern "C" SEXP _vapour_register_gdal_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(register_gdal_cpp());
  END_CPP11
}
// 00_gdal.cpp
strings version_gdal_cpp();
extern "C" SEXP _vapour_version_gdal_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(version_gdal_cpp());
  END_CPP11
}
// 00_gdal.cpp
integers version_proj_cpp();
extern "C" SEXP _vapour_version_proj_cpp() {
  BEGIN_CPP11
    return cpp11::as_sexp(version_proj_cpp());
  END_CPP11
}
// 00_gdal.cpp
strings vsi_list_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_vsi_list_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(vsi_list_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_geometry.cpp
doubles feature_count_gdal_cpp(strings dsn, integers layer, strings sql, doubles ex);
extern "C" SEXP _vapour_feature_count_gdal_cpp(SEXP dsn, SEXP layer, SEXP sql, SEXP ex) {
  BEGIN_CPP11
    return cpp11::as_sexp(feature_count_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex)));
  END_CPP11
}
// 00_geometry.cpp
list projection_info_gdal_cpp(strings dsn, integers layer, strings sql);
extern "C" SEXP _vapour_projection_info_gdal_cpp(SEXP dsn, SEXP layer, SEXP sql) {
  BEGIN_CPP11
    return cpp11::as_sexp(projection_info_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql)));
  END_CPP11
}
// 00_geometry.cpp
strings report_fields_gdal_cpp(strings dsn, integers layer, strings sql);
extern "C" SEXP _vapour_report_fields_gdal_cpp(SEXP dsn, SEXP layer, SEXP sql) {
  BEGIN_CPP11
    return cpp11::as_sexp(report_fields_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql)));
  END_CPP11
}
// 00_geometry.cpp
strings vapour_geom_name_cpp(strings dsource, integers layer, strings sql, doubles ex);
extern "C" SEXP _vapour_vapour_geom_name_cpp(SEXP dsource, SEXP layer, SEXP sql, SEXP ex) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_geom_name_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex)));
  END_CPP11
}
// 00_geometry.cpp
doubles vapour_layer_extent_cpp(strings dsource, integers layer, strings sql, doubles ex);
extern "C" SEXP _vapour_vapour_layer_extent_cpp(SEXP dsource, SEXP layer, SEXP sql, SEXP ex) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_layer_extent_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_geom_all(strings dsn, integers layer, strings sql, doubles ex, strings format);
extern "C" SEXP _vapour_gdal_dsn_read_geom_all(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP format) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_geom_all(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(format)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_geom_ij(strings dsn, integers layer, strings sql, doubles ex, strings format, doubles ij);
extern "C" SEXP _vapour_gdal_dsn_read_geom_ij(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP format, SEXP ij) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_geom_ij(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(format), cpp11::as_cpp<cpp11::decay_t<doubles>>(ij)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_geom_ia(strings dsn, integers layer, strings sql, doubles ex, strings format, doubles ia);
extern "C" SEXP _vapour_gdal_dsn_read_geom_ia(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP format, SEXP ia) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_geom_ia(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(format), cpp11::as_cpp<cpp11::decay_t<doubles>>(ia)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_geom_fa(strings dsn, integers layer, strings sql, doubles ex, strings format, doubles fa);
extern "C" SEXP _vapour_gdal_dsn_read_geom_fa(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP format, SEXP fa) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_geom_fa(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(format), cpp11::as_cpp<cpp11::decay_t<doubles>>(fa)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_fields_all(strings dsn, integers layer, strings sql, doubles ex, strings fid_column_name);
extern "C" SEXP _vapour_gdal_dsn_read_fields_all(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP fid_column_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fields_all(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(fid_column_name)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_fields_ij(strings dsn, integers layer, strings sql, doubles ex, strings fid_column_name, doubles ij);
extern "C" SEXP _vapour_gdal_dsn_read_fields_ij(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP fid_column_name, SEXP ij) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fields_ij(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(fid_column_name), cpp11::as_cpp<cpp11::decay_t<doubles>>(ij)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_fields_ia(strings dsn, integers layer, strings sql, doubles ex, strings fid_column_name, doubles ia);
extern "C" SEXP _vapour_gdal_dsn_read_fields_ia(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP fid_column_name, SEXP ia) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fields_ia(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(fid_column_name), cpp11::as_cpp<cpp11::decay_t<doubles>>(ia)));
  END_CPP11
}
// 00_geometry.cpp
list gdal_dsn_read_fields_fa(strings dsn, integers layer, strings sql, doubles ex, strings fid_column_name, doubles fa);
extern "C" SEXP _vapour_gdal_dsn_read_fields_fa(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP fid_column_name, SEXP fa) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fields_fa(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(fid_column_name), cpp11::as_cpp<cpp11::decay_t<doubles>>(fa)));
  END_CPP11
}
// 00_geometry.cpp
doubles gdal_dsn_read_fids_all(strings dsn, integers layer, strings sql, doubles ex);
extern "C" SEXP _vapour_gdal_dsn_read_fids_all(SEXP dsn, SEXP layer, SEXP sql, SEXP ex) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fids_all(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex)));
  END_CPP11
}
// 00_geometry.cpp
doubles gdal_dsn_read_fids_ij(strings dsn, integers layer, strings sql, doubles ex, doubles ij);
extern "C" SEXP _vapour_gdal_dsn_read_fids_ij(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP ij) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fids_ij(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<doubles>>(ij)));
  END_CPP11
}
// 00_geometry.cpp
doubles gdal_dsn_read_fids_ia(strings dsn, integers layer, strings sql, doubles ex, doubles ia);
extern "C" SEXP _vapour_gdal_dsn_read_fids_ia(SEXP dsn, SEXP layer, SEXP sql, SEXP ex, SEXP ia) {
  BEGIN_CPP11
    return cpp11::as_sexp(gdal_dsn_read_fids_ia(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<doubles>>(ia)));
  END_CPP11
}
// 00_geometry.cpp
list read_fields_gdal_cpp(strings dsn, integers layer, strings sql, integers limit_n, integers skip_n, doubles ex, strings fid_column_name);
extern "C" SEXP _vapour_read_fields_gdal_cpp(SEXP dsn, SEXP layer, SEXP sql, SEXP limit_n, SEXP skip_n, SEXP ex, SEXP fid_column_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_fields_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<integers>>(limit_n), cpp11::as_cpp<cpp11::decay_t<integers>>(skip_n), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex), cpp11::as_cpp<cpp11::decay_t<strings>>(fid_column_name)));
  END_CPP11
}
// 00_geometry.cpp
list read_geometry_gdal_cpp(strings dsn, integers layer, strings sql, strings what, strings textformat, integers limit_n, integers skip_n, doubles ex);
extern "C" SEXP _vapour_read_geometry_gdal_cpp(SEXP dsn, SEXP layer, SEXP sql, SEXP what, SEXP textformat, SEXP limit_n, SEXP skip_n, SEXP ex) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_geometry_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<strings>>(what), cpp11::as_cpp<cpp11::decay_t<strings>>(textformat), cpp11::as_cpp<cpp11::decay_t<integers>>(limit_n), cpp11::as_cpp<cpp11::decay_t<integers>>(skip_n), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex)));
  END_CPP11
}
// 00_geometry.cpp
doubles read_fids_gdal_cpp(strings dsn, integers layer, strings sql, integers limit_n, integers skip_n, doubles ex);
extern "C" SEXP _vapour_read_fids_gdal_cpp(SEXP dsn, SEXP layer, SEXP sql, SEXP limit_n, SEXP skip_n, SEXP ex) {
  BEGIN_CPP11
    return cpp11::as_sexp(read_fids_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(layer), cpp11::as_cpp<cpp11::decay_t<strings>>(sql), cpp11::as_cpp<cpp11::decay_t<integers>>(limit_n), cpp11::as_cpp<cpp11::decay_t<integers>>(skip_n), cpp11::as_cpp<cpp11::decay_t<doubles>>(ex)));
  END_CPP11
}
// 00_raster.cpp
list raster_gcp_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_raster_gcp_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_gcp_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_raster.cpp
logicals raster_has_geolocation_gdal_cpp(strings dsn, integers sds);
extern "C" SEXP _vapour_raster_has_geolocation_gdal_cpp(SEXP dsn, SEXP sds) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_has_geolocation_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(sds)));
  END_CPP11
}
// 00_raster.cpp
list raster_list_geolocation_gdal_cpp(strings dsn, integers sds);
extern "C" SEXP _vapour_raster_list_geolocation_gdal_cpp(SEXP dsn, SEXP sds) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_list_geolocation_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(sds)));
  END_CPP11
}
// 00_raster.cpp
list raster_info_gdal_cpp(strings dsn, logicals min_max);
extern "C" SEXP _vapour_raster_info_gdal_cpp(SEXP dsn, SEXP min_max) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_info_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<logicals>>(min_max)));
  END_CPP11
}
// 00_raster.cpp
doubles raster_extent_cpp(strings dsn);
extern "C" SEXP _vapour_raster_extent_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_extent_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_raster.cpp
list raster_io_gdal_cpp(strings dsn, integers window, integers band, strings resample, strings band_output_type, logicals unscale, logicals nara);
extern "C" SEXP _vapour_raster_io_gdal_cpp(SEXP dsn, SEXP window, SEXP band, SEXP resample, SEXP band_output_type, SEXP unscale, SEXP nara) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_io_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<integers>>(window), cpp11::as_cpp<cpp11::decay_t<integers>>(band), cpp11::as_cpp<cpp11::decay_t<strings>>(resample), cpp11::as_cpp<cpp11::decay_t<strings>>(band_output_type), cpp11::as_cpp<cpp11::decay_t<logicals>>(unscale), cpp11::as_cpp<cpp11::decay_t<logicals>>(nara)));
  END_CPP11
}
// 00_raster.cpp
strings sds_list_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_sds_list_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(sds_list_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_raster.cpp
list sds_list_list_gdal_cpp(strings dsn);
extern "C" SEXP _vapour_sds_list_list_gdal_cpp(SEXP dsn) {
  BEGIN_CPP11
    return cpp11::as_sexp(sds_list_list_gdal_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn)));
  END_CPP11
}
// 00_raster_block_io.cpp
list vapour_read_raster_block_cpp(strings dsource, integers offset, integers dimension, integers band, strings band_output_type, logicals unscale, logicals nara);
extern "C" SEXP _vapour_vapour_read_raster_block_cpp(SEXP dsource, SEXP offset, SEXP dimension, SEXP band, SEXP band_output_type, SEXP unscale, SEXP nara) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_read_raster_block_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<integers>>(offset), cpp11::as_cpp<cpp11::decay_t<integers>>(dimension), cpp11::as_cpp<cpp11::decay_t<integers>>(band), cpp11::as_cpp<cpp11::decay_t<strings>>(band_output_type), cpp11::as_cpp<cpp11::decay_t<logicals>>(unscale), cpp11::as_cpp<cpp11::decay_t<logicals>>(nara)));
  END_CPP11
}
// 00_raster_block_io.cpp
logicals vapour_write_raster_block_cpp(strings dsource, doubles data, integers offset, integers dimension, integers band, strings open_options);
extern "C" SEXP _vapour_vapour_write_raster_block_cpp(SEXP dsource, SEXP data, SEXP offset, SEXP dimension, SEXP band, SEXP open_options) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_write_raster_block_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<integers>>(offset), cpp11::as_cpp<cpp11::decay_t<integers>>(dimension), cpp11::as_cpp<cpp11::decay_t<integers>>(band), cpp11::as_cpp<cpp11::decay_t<strings>>(open_options)));
  END_CPP11
}
// 00_raster_block_io.cpp
strings vapour_create_copy_cpp(strings dsource, strings dtarget, strings driver);
extern "C" SEXP _vapour_vapour_create_copy_cpp(SEXP dsource, SEXP dtarget, SEXP driver) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_create_copy_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<strings>>(dtarget), cpp11::as_cpp<cpp11::decay_t<strings>>(driver)));
  END_CPP11
}
// 00_raster_block_io.cpp
strings vapour_create_cpp(strings filename, strings driver, doubles extent, integers dimension, strings projection, integers n_bands, strings datatype, list options_list_pairs);
extern "C" SEXP _vapour_vapour_create_cpp(SEXP filename, SEXP driver, SEXP extent, SEXP dimension, SEXP projection, SEXP n_bands, SEXP datatype, SEXP options_list_pairs) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_create_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(filename), cpp11::as_cpp<cpp11::decay_t<strings>>(driver), cpp11::as_cpp<cpp11::decay_t<doubles>>(extent), cpp11::as_cpp<cpp11::decay_t<integers>>(dimension), cpp11::as_cpp<cpp11::decay_t<strings>>(projection), cpp11::as_cpp<cpp11::decay_t<integers>>(n_bands), cpp11::as_cpp<cpp11::decay_t<strings>>(datatype), cpp11::as_cpp<cpp11::decay_t<list>>(options_list_pairs)));
  END_CPP11
}
// 00_raster_block_io.cpp
doubles vapour_read_raster_value_cpp(strings dsource, integers col, integers row, integers band, strings band_output_type);
extern "C" SEXP _vapour_vapour_read_raster_value_cpp(SEXP dsource, SEXP col, SEXP row, SEXP band, SEXP band_output_type) {
  BEGIN_CPP11
    return cpp11::as_sexp(vapour_read_raster_value_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<integers>>(col), cpp11::as_cpp<cpp11::decay_t<integers>>(row), cpp11::as_cpp<cpp11::decay_t<integers>>(band), cpp11::as_cpp<cpp11::decay_t<strings>>(band_output_type)));
  END_CPP11
}
// 00_raster_block_io.cpp
list blocks_cpp1(strings dsource, integers iblock, logicals read);
extern "C" SEXP _vapour_blocks_cpp1(SEXP dsource, SEXP iblock, SEXP read) {
  BEGIN_CPP11
    return cpp11::as_sexp(blocks_cpp1(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<integers>>(iblock), cpp11::as_cpp<cpp11::decay_t<logicals>>(read)));
  END_CPP11
}
// 00_raster_block_io.cpp
list blocks_cpp(strings dsource, integers iblock, logicals read);
extern "C" SEXP _vapour_blocks_cpp(SEXP dsource, SEXP iblock, SEXP read) {
  BEGIN_CPP11
    return cpp11::as_sexp(blocks_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsource), cpp11::as_cpp<cpp11::decay_t<integers>>(iblock), cpp11::as_cpp<cpp11::decay_t<logicals>>(read)));
  END_CPP11
}
// 00_utils.cpp
strings raster_gdalinfo_app_cpp(strings dsn, strings options);
extern "C" SEXP _vapour_raster_gdalinfo_app_cpp(SEXP dsn, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_gdalinfo_app_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<strings>>(options)));
  END_CPP11
}
// 00_vrt.cpp
strings raster_vrt_cpp(strings dsn, doubles extent, strings projection, integers sds, integers bands, strings geolocation, logicals nomd, integers overview, strings options);
extern "C" SEXP _vapour_raster_vrt_cpp(SEXP dsn, SEXP extent, SEXP projection, SEXP sds, SEXP bands, SEXP geolocation, SEXP nomd, SEXP overview, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_vrt_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(dsn), cpp11::as_cpp<cpp11::decay_t<doubles>>(extent), cpp11::as_cpp<cpp11::decay_t<strings>>(projection), cpp11::as_cpp<cpp11::decay_t<integers>>(sds), cpp11::as_cpp<cpp11::decay_t<integers>>(bands), cpp11::as_cpp<cpp11::decay_t<strings>>(geolocation), cpp11::as_cpp<cpp11::decay_t<logicals>>(nomd), cpp11::as_cpp<cpp11::decay_t<integers>>(overview), cpp11::as_cpp<cpp11::decay_t<strings>>(options)));
  END_CPP11
}
// 00_vrt.cpp
strings raster_buildvrt_cpp(std::vector<std::string> dsn, std::vector<std::string> options);
extern "C" SEXP _vapour_raster_buildvrt_cpp(SEXP dsn, SEXP options) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_buildvrt_cpp(cpp11::as_cpp<cpp11::decay_t<std::vector<std::string>>>(dsn), cpp11::as_cpp<cpp11::decay_t<std::vector<std::string>>>(options)));
  END_CPP11
}
// warp_file.cpp
list raster_warp_file_cpp(strings source_filename, strings target_crs, doubles target_extent, integers target_dim, strings target_filename, integers bands, strings resample, logicals silent, strings band_output_type, strings warp_options, strings transformation_options);
extern "C" SEXP _vapour_raster_warp_file_cpp(SEXP source_filename, SEXP target_crs, SEXP target_extent, SEXP target_dim, SEXP target_filename, SEXP bands, SEXP resample, SEXP silent, SEXP band_output_type, SEXP warp_options, SEXP transformation_options) {
  BEGIN_CPP11
    return cpp11::as_sexp(raster_warp_file_cpp(cpp11::as_cpp<cpp11::decay_t<strings>>(source_filename), cpp11::as_cpp<cpp11::decay_t<strings>>(target_crs), cpp11::as_cpp<cpp11::decay_t<doubles>>(target_extent), cpp11::as_cpp<cpp11::decay_t<integers>>(target_dim), cpp11::as_cpp<cpp11::decay_t<strings>>(target_filename), cpp11::as_cpp<cpp11::decay_t<integers>>(bands), cpp11::as_cpp<cpp11::decay_t<strings>>(resample), cpp11::as_cpp<cpp11::decay_t<logicals>>(silent), cpp11::as_cpp<cpp11::decay_t<strings>>(band_output_type), cpp11::as_cpp<cpp11::decay_t<strings>>(warp_options), cpp11::as_cpp<cpp11::decay_t<strings>>(transformation_options)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_vapour_blocks_cpp",                       (DL_FUNC) &_vapour_blocks_cpp,                        3},
    {"_vapour_blocks_cpp1",                      (DL_FUNC) &_vapour_blocks_cpp1,                       3},
    {"_vapour_cleanup_gdal_cpp",                 (DL_FUNC) &_vapour_cleanup_gdal_cpp,                  0},
    {"_vapour_crs_is_lonlat_cpp",                (DL_FUNC) &_vapour_crs_is_lonlat_cpp,                 1},
    {"_vapour_driver_gdal_cpp",                  (DL_FUNC) &_vapour_driver_gdal_cpp,                   1},
    {"_vapour_driver_id_gdal_cpp",               (DL_FUNC) &_vapour_driver_id_gdal_cpp,                1},
    {"_vapour_drivers_list_gdal_cpp",            (DL_FUNC) &_vapour_drivers_list_gdal_cpp,             0},
    {"_vapour_feature_count_gdal_cpp",           (DL_FUNC) &_vapour_feature_count_gdal_cpp,            4},
    {"_vapour_gdal_dsn_read_fids_all",           (DL_FUNC) &_vapour_gdal_dsn_read_fids_all,            4},
    {"_vapour_gdal_dsn_read_fids_ia",            (DL_FUNC) &_vapour_gdal_dsn_read_fids_ia,             5},
    {"_vapour_gdal_dsn_read_fids_ij",            (DL_FUNC) &_vapour_gdal_dsn_read_fids_ij,             5},
    {"_vapour_gdal_dsn_read_fields_all",         (DL_FUNC) &_vapour_gdal_dsn_read_fields_all,          5},
    {"_vapour_gdal_dsn_read_fields_fa",          (DL_FUNC) &_vapour_gdal_dsn_read_fields_fa,           6},
    {"_vapour_gdal_dsn_read_fields_ia",          (DL_FUNC) &_vapour_gdal_dsn_read_fields_ia,           6},
    {"_vapour_gdal_dsn_read_fields_ij",          (DL_FUNC) &_vapour_gdal_dsn_read_fields_ij,           6},
    {"_vapour_gdal_dsn_read_geom_all",           (DL_FUNC) &_vapour_gdal_dsn_read_geom_all,            5},
    {"_vapour_gdal_dsn_read_geom_fa",            (DL_FUNC) &_vapour_gdal_dsn_read_geom_fa,             6},
    {"_vapour_gdal_dsn_read_geom_ia",            (DL_FUNC) &_vapour_gdal_dsn_read_geom_ia,             6},
    {"_vapour_gdal_dsn_read_geom_ij",            (DL_FUNC) &_vapour_gdal_dsn_read_geom_ij,             6},
    {"_vapour_gdal_dsn_read_vector_stream",      (DL_FUNC) &_vapour_gdal_dsn_read_vector_stream,      11},
    {"_vapour_get_gdal_config_cpp",              (DL_FUNC) &_vapour_get_gdal_config_cpp,               1},
    {"_vapour_layer_names_gdal_cpp",             (DL_FUNC) &_vapour_layer_names_gdal_cpp,              1},
    {"_vapour_proj_to_wkt_gdal_cpp",             (DL_FUNC) &_vapour_proj_to_wkt_gdal_cpp,              1},
    {"_vapour_projection_info_gdal_cpp",         (DL_FUNC) &_vapour_projection_info_gdal_cpp,          3},
    {"_vapour_raster_buildvrt_cpp",              (DL_FUNC) &_vapour_raster_buildvrt_cpp,               2},
    {"_vapour_raster_extent_cpp",                (DL_FUNC) &_vapour_raster_extent_cpp,                 1},
    {"_vapour_raster_gcp_gdal_cpp",              (DL_FUNC) &_vapour_raster_gcp_gdal_cpp,               1},
    {"_vapour_raster_gdalinfo_app_cpp",          (DL_FUNC) &_vapour_raster_gdalinfo_app_cpp,           2},
    {"_vapour_raster_has_geolocation_gdal_cpp",  (DL_FUNC) &_vapour_raster_has_geolocation_gdal_cpp,   2},
    {"_vapour_raster_info_gdal_cpp",             (DL_FUNC) &_vapour_raster_info_gdal_cpp,              2},
    {"_vapour_raster_io_gdal_cpp",               (DL_FUNC) &_vapour_raster_io_gdal_cpp,                7},
    {"_vapour_raster_list_geolocation_gdal_cpp", (DL_FUNC) &_vapour_raster_list_geolocation_gdal_cpp,  2},
    {"_vapour_raster_vrt_cpp",                   (DL_FUNC) &_vapour_raster_vrt_cpp,                    9},
    {"_vapour_raster_warp_file_cpp",             (DL_FUNC) &_vapour_raster_warp_file_cpp,             11},
    {"_vapour_read_fids_gdal_cpp",               (DL_FUNC) &_vapour_read_fids_gdal_cpp,                6},
    {"_vapour_read_fields_gdal_cpp",             (DL_FUNC) &_vapour_read_fields_gdal_cpp,              7},
    {"_vapour_read_geometry_gdal_cpp",           (DL_FUNC) &_vapour_read_geometry_gdal_cpp,            8},
    {"_vapour_register_gdal_cpp",                (DL_FUNC) &_vapour_register_gdal_cpp,                 0},
    {"_vapour_report_fields_gdal_cpp",           (DL_FUNC) &_vapour_report_fields_gdal_cpp,            3},
    {"_vapour_sds_list_gdal_cpp",                (DL_FUNC) &_vapour_sds_list_gdal_cpp,                 1},
    {"_vapour_sds_list_list_gdal_cpp",           (DL_FUNC) &_vapour_sds_list_list_gdal_cpp,            1},
    {"_vapour_set_gdal_config_cpp",              (DL_FUNC) &_vapour_set_gdal_config_cpp,               2},
    {"_vapour_vapour_create_copy_cpp",           (DL_FUNC) &_vapour_vapour_create_copy_cpp,            3},
    {"_vapour_vapour_create_cpp",                (DL_FUNC) &_vapour_vapour_create_cpp,                 8},
    {"_vapour_vapour_geom_name_cpp",             (DL_FUNC) &_vapour_vapour_geom_name_cpp,              4},
    {"_vapour_vapour_layer_extent_cpp",          (DL_FUNC) &_vapour_vapour_layer_extent_cpp,           4},
    {"_vapour_vapour_read_raster_block_cpp",     (DL_FUNC) &_vapour_vapour_read_raster_block_cpp,      7},
    {"_vapour_vapour_read_raster_value_cpp",     (DL_FUNC) &_vapour_vapour_read_raster_value_cpp,      5},
    {"_vapour_vapour_write_raster_block_cpp",    (DL_FUNC) &_vapour_vapour_write_raster_block_cpp,     6},
    {"_vapour_version_gdal_cpp",                 (DL_FUNC) &_vapour_version_gdal_cpp,                  0},
    {"_vapour_version_proj_cpp",                 (DL_FUNC) &_vapour_version_proj_cpp,                  0},
    {"_vapour_vsi_list_gdal_cpp",                (DL_FUNC) &_vapour_vsi_list_gdal_cpp,                 1},
    {"_vapour_warp_general_cpp",                 (DL_FUNC) &_vapour_warp_general_cpp,                 13},
    {"_vapour_warp_suggest_cpp",                 (DL_FUNC) &_vapour_warp_suggest_cpp,                  2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_vapour(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
