# Generated by cpp11: do not edit by hand

gdal_dsn_read_vector_stream <- function(stream_xptr, dsn, layer, sql, options, quiet, drivers, extent, dsn_exists, fid_column_name, width) {
  .Call(`_vapour_gdal_dsn_read_vector_stream`, stream_xptr, dsn, layer, sql, options, quiet, drivers, extent, dsn_exists, fid_column_name, width)
}

warp_general_cpp <- function(dsn, target_crs, target_extent, target_dim, target_res, bands, resample, silent, band_output_type, options, dsn_outname, include_meta, nara) {
  .Call(`_vapour_warp_general_cpp`, dsn, target_crs, target_extent, target_dim, target_res, bands, resample, silent, band_output_type, options, dsn_outname, include_meta, nara)
}

warp_suggest_cpp <- function(dsn, target_crs) {
  .Call(`_vapour_warp_suggest_cpp`, dsn, target_crs)
}

set_gdal_config_cpp <- function(option, value) {
  .Call(`_vapour_set_gdal_config_cpp`, option, value)
}

get_gdal_config_cpp <- function(option) {
  .Call(`_vapour_get_gdal_config_cpp`, option)
}

cleanup_gdal_cpp <- function() {
  .Call(`_vapour_cleanup_gdal_cpp`)
}

driver_gdal_cpp <- function(dsn) {
  .Call(`_vapour_driver_gdal_cpp`, dsn)
}

driver_id_gdal_cpp <- function(dsn) {
  .Call(`_vapour_driver_id_gdal_cpp`, dsn)
}

layer_names_gdal_cpp <- function(dsn) {
  .Call(`_vapour_layer_names_gdal_cpp`, dsn)
}

drivers_list_gdal_cpp <- function() {
  .Call(`_vapour_drivers_list_gdal_cpp`)
}

proj_to_wkt_gdal_cpp <- function(proj4string) {
  .Call(`_vapour_proj_to_wkt_gdal_cpp`, proj4string)
}

crs_is_lonlat_cpp <- function(input_string) {
  .Call(`_vapour_crs_is_lonlat_cpp`, input_string)
}

register_gdal_cpp <- function() {
  .Call(`_vapour_register_gdal_cpp`)
}

version_gdal_cpp <- function() {
  .Call(`_vapour_version_gdal_cpp`)
}

version_proj_cpp <- function() {
  .Call(`_vapour_version_proj_cpp`)
}

vsi_list_gdal_cpp <- function(dsn) {
  .Call(`_vapour_vsi_list_gdal_cpp`, dsn)
}

feature_count_gdal_cpp <- function(dsn, layer, sql, ex) {
  .Call(`_vapour_feature_count_gdal_cpp`, dsn, layer, sql, ex)
}

projection_info_gdal_cpp <- function(dsn, layer, sql) {
  .Call(`_vapour_projection_info_gdal_cpp`, dsn, layer, sql)
}

report_fields_gdal_cpp <- function(dsn, layer, sql) {
  .Call(`_vapour_report_fields_gdal_cpp`, dsn, layer, sql)
}

vapour_geom_name_cpp <- function(dsource, layer, sql, ex) {
  .Call(`_vapour_vapour_geom_name_cpp`, dsource, layer, sql, ex)
}

vapour_layer_extent_cpp <- function(dsource, layer, sql, ex) {
  .Call(`_vapour_vapour_layer_extent_cpp`, dsource, layer, sql, ex)
}

gdal_dsn_read_geom_all <- function(dsn, layer, sql, ex, format) {
  .Call(`_vapour_gdal_dsn_read_geom_all`, dsn, layer, sql, ex, format)
}

gdal_dsn_read_geom_ij <- function(dsn, layer, sql, ex, format, ij) {
  .Call(`_vapour_gdal_dsn_read_geom_ij`, dsn, layer, sql, ex, format, ij)
}

gdal_dsn_read_geom_ia <- function(dsn, layer, sql, ex, format, ia) {
  .Call(`_vapour_gdal_dsn_read_geom_ia`, dsn, layer, sql, ex, format, ia)
}

gdal_dsn_read_geom_fa <- function(dsn, layer, sql, ex, format, fa) {
  .Call(`_vapour_gdal_dsn_read_geom_fa`, dsn, layer, sql, ex, format, fa)
}

gdal_dsn_read_fields_all <- function(dsn, layer, sql, ex, fid_column_name) {
  .Call(`_vapour_gdal_dsn_read_fields_all`, dsn, layer, sql, ex, fid_column_name)
}

gdal_dsn_read_fields_ij <- function(dsn, layer, sql, ex, fid_column_name, ij) {
  .Call(`_vapour_gdal_dsn_read_fields_ij`, dsn, layer, sql, ex, fid_column_name, ij)
}

gdal_dsn_read_fields_ia <- function(dsn, layer, sql, ex, fid_column_name, ia) {
  .Call(`_vapour_gdal_dsn_read_fields_ia`, dsn, layer, sql, ex, fid_column_name, ia)
}

gdal_dsn_read_fields_fa <- function(dsn, layer, sql, ex, fid_column_name, fa) {
  .Call(`_vapour_gdal_dsn_read_fields_fa`, dsn, layer, sql, ex, fid_column_name, fa)
}

gdal_dsn_read_fids_all <- function(dsn, layer, sql, ex) {
  .Call(`_vapour_gdal_dsn_read_fids_all`, dsn, layer, sql, ex)
}

gdal_dsn_read_fids_ij <- function(dsn, layer, sql, ex, ij) {
  .Call(`_vapour_gdal_dsn_read_fids_ij`, dsn, layer, sql, ex, ij)
}

gdal_dsn_read_fids_ia <- function(dsn, layer, sql, ex, ia) {
  .Call(`_vapour_gdal_dsn_read_fids_ia`, dsn, layer, sql, ex, ia)
}

read_fields_gdal_cpp <- function(dsn, layer, sql, limit_n, skip_n, ex, fid_column_name) {
  .Call(`_vapour_read_fields_gdal_cpp`, dsn, layer, sql, limit_n, skip_n, ex, fid_column_name)
}

read_geometry_gdal_cpp <- function(dsn, layer, sql, what, textformat, limit_n, skip_n, ex) {
  .Call(`_vapour_read_geometry_gdal_cpp`, dsn, layer, sql, what, textformat, limit_n, skip_n, ex)
}

read_fids_gdal_cpp <- function(dsn, layer, sql, limit_n, skip_n, ex) {
  .Call(`_vapour_read_fids_gdal_cpp`, dsn, layer, sql, limit_n, skip_n, ex)
}

raster_gcp_gdal_cpp <- function(dsn) {
  .Call(`_vapour_raster_gcp_gdal_cpp`, dsn)
}

raster_has_geolocation_gdal_cpp <- function(dsn, sds) {
  .Call(`_vapour_raster_has_geolocation_gdal_cpp`, dsn, sds)
}

raster_list_geolocation_gdal_cpp <- function(dsn, sds) {
  .Call(`_vapour_raster_list_geolocation_gdal_cpp`, dsn, sds)
}

raster_info_gdal_cpp <- function(dsn, min_max) {
  .Call(`_vapour_raster_info_gdal_cpp`, dsn, min_max)
}

raster_extent_cpp <- function(dsn) {
  .Call(`_vapour_raster_extent_cpp`, dsn)
}

raster_io_gdal_cpp <- function(dsn, window, band, resample, band_output_type, unscale, nara) {
  .Call(`_vapour_raster_io_gdal_cpp`, dsn, window, band, resample, band_output_type, unscale, nara)
}

sds_list_gdal_cpp <- function(dsn) {
  .Call(`_vapour_sds_list_gdal_cpp`, dsn)
}

sds_list_list_gdal_cpp <- function(dsn) {
  .Call(`_vapour_sds_list_list_gdal_cpp`, dsn)
}

vapour_read_raster_block_cpp <- function(dsource, offset, dimension, band, band_output_type, unscale, nara) {
  .Call(`_vapour_vapour_read_raster_block_cpp`, dsource, offset, dimension, band, band_output_type, unscale, nara)
}

vapour_write_raster_block_cpp <- function(dsource, data, offset, dimension, band, open_options) {
  .Call(`_vapour_vapour_write_raster_block_cpp`, dsource, data, offset, dimension, band, open_options)
}

vapour_create_copy_cpp <- function(dsource, dtarget, driver) {
  .Call(`_vapour_vapour_create_copy_cpp`, dsource, dtarget, driver)
}

vapour_create_cpp <- function(filename, driver, extent, dimension, projection, n_bands, datatype, options_list_pairs) {
  .Call(`_vapour_vapour_create_cpp`, filename, driver, extent, dimension, projection, n_bands, datatype, options_list_pairs)
}

vapour_read_raster_value_cpp <- function(dsource, col, row, band, band_output_type) {
  .Call(`_vapour_vapour_read_raster_value_cpp`, dsource, col, row, band, band_output_type)
}

blocks_cpp1 <- function(dsource, iblock, read) {
  .Call(`_vapour_blocks_cpp1`, dsource, iblock, read)
}

blocks_cpp <- function(dsource, iblock, read) {
  .Call(`_vapour_blocks_cpp`, dsource, iblock, read)
}

raster_gdalinfo_app_cpp <- function(dsn, options) {
  .Call(`_vapour_raster_gdalinfo_app_cpp`, dsn, options)
}

raster_vrt_cpp <- function(dsn, extent, projection, sds, bands, geolocation, nomd, overview, options) {
  .Call(`_vapour_raster_vrt_cpp`, dsn, extent, projection, sds, bands, geolocation, nomd, overview, options)
}

raster_buildvrt_cpp <- function(dsn, options) {
  .Call(`_vapour_raster_buildvrt_cpp`, dsn, options)
}

raster_warp_file_cpp <- function(source_filename, target_crs, target_extent, target_dim, target_filename, bands, resample, silent, band_output_type, warp_options, transformation_options) {
  .Call(`_vapour_raster_warp_file_cpp`, source_filename, target_crs, target_extent, target_dim, target_filename, bands, resample, silent, band_output_type, warp_options, transformation_options)
}
