# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Raster IO
#'
#' @export
#' @examples
#' f <- system.file("extdata", "volcano.tif", package = "vapour")
#' fact <- 2
#' m <- matrix(rasterio(f, fact), ncol(volcano)/fact)
#' image(m)
#' contour(t(volcano), add = TRUE)
rasterio <- function(pszFilename, subfact = 5L) {
    .Call('_vapour_rasterio', PACKAGE = 'vapour', pszFilename, subfact)
}

#'  GDAL geometry bounding box
#'
#' Read a GDAL geometry summary as just the native bounding box.
#'
#' @param dsource data source name (path to file, connection string, URL)
#' @param layer integer of layer to work with, defaults to the first (0)
#' @examples
#' sfile <- system.file("shape/nc.shp", package="sf")
#' to_bblob(sfile)
#' @export
to_bblob <- function(dsource, layer = 0L) {
    .Call('_vapour_to_bblob', PACKAGE = 'vapour', dsource, layer)
}

#' Test GDAL read
#'
#' Simple pointless function to learn the GDAL API.
#'
#' Microprocessors, databases, servers.
#' @param dsource data source name (path to file, connection string, URL)
#' @param layer integer of layer to work with, defaults to the first (0)
#' @examples
#' sfile <- system.file("shape/nc.shp", package="sf")
#' vapour(sfile)
#' pfile <- "inst/extdata/point.shp"
#' vapour(pfile)
#' @export
vapour <- function(dsource, layer = 0L) {
    .Call('_vapour_vapour', PACKAGE = 'vapour', dsource, layer)
}

#' Read GDAL geometry as blob
#'
#' Simple read of geometry-only as WKB format.
#'
#'
#' @param dsource data source name (path to file, connection string, URL)
#' @param layer integer of layer to work with, defaults to the first (0)
#' @format indicate text output format, available are "json" (default), "gml", "kml", "wkt"
#' @examples
#' sfile <- system.file("shape/nc.shp", package="sf")
#' tib <- tibble::tibble(wkb = to_binary(sfile)) %>% bind_cols(read_gdal_table(sfile))
#' pfile <- "inst/extdata/point.shp"
#' to_binary(pfile)
#' @export
to_binary <- function(dsource, layer = 0L) {
    .Call('_vapour_to_binary', PACKAGE = 'vapour', dsource, layer)
}

#' Read GDAL geometry as text
#'
#' Simple read of geometry-only as text format.
#'
#' Microprocessors, databases, servers.
#' @param dsource data source name (path to file, connection string, URL)
#' @param layer integer of layer to work with, defaults to the first (0)
#' @format indicate text output format, available are "json" (default), "gml", "kml", "wkt"
#' @examples
#' sfile <- system.file("shape/nc.shp", package="sf")
#' to_format(sfile)
#' pfile <- "inst/extdata/point.shp"
#' to_format(pfile)
#' @export
to_format <- function(dsource, layer = 0L, format = "json") {
    .Call('_vapour_to_format', PACKAGE = 'vapour', dsource, layer, format)
}

#' Vector attributes read
#'
#' Read layer attributes, optionally after SQL select
#' @param dsource data source name (path to file, connection string, URL)
#' @param layer integer of layer to work with, defaults to the first (0)
#' @param sql if not empty this is executed against the data source (layer will be ignored)
#' @examples
#' sfile <- system.file("shape/nc.shp", package="sf")
#' vapour_read_attributes(sfile)
#' vapour_read_attributes(sfile, sql = "SELECT * FROM nc WHERE FID < 5")
#'
#' pfile <- "inst/extdata/point.shp"
#' vapour(pfile)
#' @export
vapour_read_attributes <- function(dsource, layer = 0L, sql = "") {
    .Call('_vapour_vapour_read_attributes', PACKAGE = 'vapour', dsource, layer, sql)
}

