# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

raster_info_cpp <- function(pszFilename) {
    .Call('_vapour_raster_info_cpp', PACKAGE = 'vapour', pszFilename)
}

raster_io_cpp <- function(filename, window, band = 1L, resample = "nearestneighbour") {
    .Call('_vapour_raster_io_cpp', PACKAGE = 'vapour', filename, window, band, resample)
}

sds_info_cpp <- function(pszFilename) {
    .Call('_vapour_sds_info_cpp', PACKAGE = 'vapour', pszFilename)
}

vapour_layer_names_cpp <- function(dsource, sql = "") {
    .Call('_vapour_vapour_layer_names_cpp', PACKAGE = 'vapour', dsource, sql)
}

vapour_read_attributes_cpp <- function(dsource, layer = 0L, sql = "") {
    .Call('_vapour_vapour_read_attributes_cpp', PACKAGE = 'vapour', dsource, layer, sql)
}

vapour_read_geometry_cpp <- function(dsource, layer = 0L, sql = "", what = "geometry", textformat = "json") {
    .Call('_vapour_vapour_read_geometry_cpp', PACKAGE = 'vapour', dsource, layer, sql, what, textformat)
}

vapour_projection_info_cpp <- function(dsource, layer = 0L, sql = "") {
    .Call('_vapour_vapour_projection_info_cpp', PACKAGE = 'vapour', dsource, layer, sql)
}

